export const runtime="nodejs";export const dynamic="force-dynamic";
const SS_BASE="https://drop.spaceseller.ma/api/v1";
function sbHeaders(){return{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY||"",Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY||""}`,"Content-Type":"application/json"};}
async function fetchTrackedIds(){const r=await fetch(`${process.env.SUPABASE_URL}/rest/v1/ss_tracked_ids?select=order_id&order=order_id.desc&limit=2000`,{headers:sbHeaders(),cache:"no-store"});if(!r.ok)return[];const a=await r.json();return a.map(row=>row.order_id);}
async function fetchOne(id){const r=await fetch(`${SS_BASE}/orders/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${process.env.SPACESELLER_TOKEN||""}`,Accept:"application/json"},cache:"no-store"});const t=await r.text();let j;try{j=JSON.parse(t);}catch{return{ok:false,status:r.status};}if(r.ok&&j?.success&&j.data)return{ok:true,data:j.data};return{ok:false,status:r.status};}
function flatten(o){return{order_id:o.order_id,uuid:o.uuid||null,fullname:o.fullname||null,phone:o.phone||null,address:o.address||null,city:o.city||null,total_price:parseFloat(o.total_price||0),tracking_number:o.tracking_number||null,order_status_code:o.order_status?.code||null,order_status_label:o.order_status?.label||null,delivery_status_code:o.delivery_status?.code||null,delivery_status_label:o.delivery_status?.label||null,date_order:o.date_order||null,products:o.products||[],raw_payload:o,synced_at:new Date().toISOString()};}
async function upsertOrders(rows){if(!rows.length)return;const r=await fetch(`${process.env.SUPABASE_URL}/rest/v1/ss_orders?on_conflict=order_id`,{method:"POST",headers:{...sbHeaders(),Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(rows)});if(!r.ok)throw new Error(`Supabase upsert HTTP ${r.status}`);}
export async function POST(req){try{if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)return Response.json({success:false,error:"env vars missing"},{status:500});const u=new URL(req.url);const idsParam=u.searchParams.get("ids")||"";let ids=idsParam.split(/[,\s]+/).map(s=>parseInt(s.trim(),10)).filter(n=>Number.isFinite(n));if(!ids.length)ids=await fetchTrackedIds();if(!ids.length)return Response.json({success:true,synced:0,message:"no tracked ids"});const ok=[];const errors=[];for(let i=0;i<ids.length;i+=4){const batch=ids.slice(i,i+4);const results=await Promise.all(batch.map(fetchOne));results.forEach((r,k)=>{if(r.ok)ok.push(flatten(r.data));else errors.push({id:batch[k]});});await new Promise(rr=>setTimeout(rr,250));}if(ok.length)await upsertOrders(ok);return Response.json({success:true,requested:ids.length,synced:ok.length,errors:errors.length});}catch(err){return Response.json({success:false,error:err.message},{status:500});}}
export const GET=POST;
